global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

alerting:

scrape_configs:
  - job_name: "graphnode-metrics"
    static_configs:
      - targets: ["graphnode-indexer-1:8040", "graphnode-query-1:8040"]
  - job_name: "indexer-service-metrics"
    static_configs:
      - targets: ["indexer-service:7300"]
  - job_name: "indexer-agent-metrics"
    static_configs:
      - targets: ["indexer-agent:7300"]
